---
- hosts: all
  become: yes
  vars_prompt:
    - name: ollama_model
      prompt: "Enter the Ollama model name you want to remove (e.g., llama3, mistral, gemma, phi)"
      private: no

  tasks:
    - name: Remove the specified Ollama model
      ansible.builtin.command:
        cmd: "ollama rm {{ ollama_model }}"
      register: ollama_output
      changed_when: "'deleted' in ollama_output.stdout"

    - name: Display confirmation
      ansible.builtin.debug:
        msg: "Successfully removed model: {{ ollama_model }}"


